"""
core/state.py

Defines the shared AgentState (ResearchState) used across all LangGraph nodes.
This is the single source of truth for data flowing through the graph.
"""

from typing import TypedDict


class ResearchState(TypedDict):
    """
    Shared state passed between all nodes in the LangGraph pipeline.

    Fields:
        query           : The original research topic from the user.
        sub_questions   : 3–5 focused sub-questions generated by the planner.
        search_results  : Raw search results per sub-question (list of result lists).
        summaries       : Condensed summaries of filtered search results.
        consistency_report : Report highlighting contradictions or gaps in summaries.
        final_report    : The complete, structured markdown research report.
    """

    query: str
    sub_questions: list[str]
    search_results: list[list[dict]]
    summaries: list[str]
    consistency_report: str
    final_report: str
